// ============================================================
// Audit event type and category constants.
// Single source of truth — add new events here only.
// ============================================================

export const AuditCategory = {
  ACCESS: 'ACCESS',
  CONTACT: 'CONTACT',
  CONVERSATION: 'CONVERSATION',
  COMMUNICATION: 'COMMUNICATION',
  DATA: 'DATA',
  AUTHENTICATION: 'AUTHENTICATION',
  ADMIN: 'ADMIN',
  BUSINESS: 'BUSINESS',
  SUPPORT: 'SUPPORT',
} as const;

export type AuditCategoryValue = (typeof AuditCategory)[keyof typeof AuditCategory];

export const AuditEventType = {
  // Contact access
  CONTACT_VIEWED: 'CONTACT_VIEWED',
  CONTACT_PHONE_REVEALED: 'CONTACT_PHONE_REVEALED',
  CONTACT_PHONE_COPIED: 'CONTACT_PHONE_COPIED',
  CONTACT_EMAIL_VIEWED: 'CONTACT_EMAIL_VIEWED',

  // Communication actions
  CONTACT_CALL_CLICKED: 'CONTACT_CALL_CLICKED',
  CONTACT_WHATSAPP_CLICKED: 'CONTACT_WHATSAPP_CLICKED',

  // Conversation access
  CONVERSATION_VIEWED: 'CONVERSATION_VIEWED',
  CONVERSATION_CONTACT_OPENED: 'CONVERSATION_CONTACT_OPENED',

  // Contact modification (via DB trigger)
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',

  // Data export (reserved for future use)
  CONTACT_EXPORT_REQUESTED: 'CONTACT_EXPORT_REQUESTED',
  CONTACT_EXPORT_COMPLETED: 'CONTACT_EXPORT_COMPLETED',

  // Customer consent (Terms of Service / Privacy Policy)
  CONSENT_ACCEPTED: 'CONSENT_ACCEPTED',
  CONSENT_DECLINED: 'CONSENT_DECLINED',

  // Customer data rights (public form: download / delete)
  DATA_DELETION_REQUESTED: 'DATA_DELETION_REQUESTED',
  DATA_ANONYMISED: 'DATA_ANONYMISED',

  // Business classification and capabilities
  BUSINESS_TYPE_CHANGED: 'BUSINESS_TYPE_CHANGED',
  CAPABILITY_ENABLED: 'CAPABILITY_ENABLED',
  CAPABILITY_DISABLED: 'CAPABILITY_DISABLED',

  // Offerings/Catalog
  OFFERING_CREATED: 'OFFERING_CREATED',
  OFFERING_UPDATED: 'OFFERING_UPDATED',
  OFFERING_ARCHIVED: 'OFFERING_ARCHIVED',
  OFFERING_RESTORED: 'OFFERING_RESTORED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',

  // Catalogue service
  CATALOGUE_ITEM_VIEWED: 'CATALOGUE_ITEM_VIEWED',
  CATALOGUE_SEARCH_PERFORMED: 'CATALOGUE_SEARCH_PERFORMED',
  CATALOGUE_SOURCE_CONNECTED: 'CATALOGUE_SOURCE_CONNECTED',
  CATALOGUE_BROWSE_PERFORMED: 'CATALOGUE_BROWSE_PERFORMED',

  // WhatsApp settings protection (password-gated tab)
  WHATSAPP_SETTINGS_UNLOCKED: 'WHATSAPP_SETTINGS_UNLOCKED',
  WHATSAPP_CONFIG_RESET: 'WHATSAPP_CONFIG_RESET',

  // Support helpdesk (tickets raised about the product itself)
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLIED: 'SUPPORT_TICKET_REPLIED',
  SUPPORT_TICKET_STATUS_CHANGED: 'SUPPORT_TICKET_STATUS_CHANGED',

  // B2B terms acceptance (business owner accepts platform Terms)
  TERMS_ACCEPTED: 'TERMS_ACCEPTED',
} as const;

export type AuditEventTypeValue = (typeof AuditEventType)[keyof typeof AuditEventType];

/** Map event types to their categories. */
export const EVENT_CATEGORY_MAP: Record<AuditEventTypeValue, AuditCategoryValue> = {
  CONTACT_VIEWED: AuditCategory.ACCESS,
  CONTACT_PHONE_REVEALED: AuditCategory.ACCESS,
  CONTACT_PHONE_COPIED: AuditCategory.ACCESS,
  CONTACT_EMAIL_VIEWED: AuditCategory.ACCESS,
  CONTACT_CALL_CLICKED: AuditCategory.COMMUNICATION,
  CONTACT_WHATSAPP_CLICKED: AuditCategory.COMMUNICATION,
  CONVERSATION_VIEWED: AuditCategory.CONVERSATION,
  CONVERSATION_CONTACT_OPENED: AuditCategory.CONVERSATION,
  CONTACT_CREATED: AuditCategory.CONTACT,
  CONTACT_UPDATED: AuditCategory.CONTACT,
  CONTACT_DELETED: AuditCategory.CONTACT,
  CONTACT_EXPORT_REQUESTED: AuditCategory.DATA,
  CONTACT_EXPORT_COMPLETED: AuditCategory.DATA,
  CONSENT_ACCEPTED: AuditCategory.DATA,
  CONSENT_DECLINED: AuditCategory.DATA,
  DATA_DELETION_REQUESTED: AuditCategory.DATA,
  DATA_ANONYMISED: AuditCategory.DATA,
  BUSINESS_TYPE_CHANGED: AuditCategory.BUSINESS,
  CAPABILITY_ENABLED: AuditCategory.BUSINESS,
  CAPABILITY_DISABLED: AuditCategory.BUSINESS,
  OFFERING_CREATED: AuditCategory.BUSINESS,
  OFFERING_UPDATED: AuditCategory.BUSINESS,
  OFFERING_ARCHIVED: AuditCategory.BUSINESS,
  OFFERING_RESTORED: AuditCategory.BUSINESS,
  CATEGORY_CREATED: AuditCategory.BUSINESS,
  CATEGORY_UPDATED: AuditCategory.BUSINESS,
  CATEGORY_DELETED: AuditCategory.BUSINESS,
  CATALOGUE_ITEM_VIEWED: AuditCategory.BUSINESS,
  CATALOGUE_SEARCH_PERFORMED: AuditCategory.BUSINESS,
  CATALOGUE_SOURCE_CONNECTED: AuditCategory.BUSINESS,
  CATALOGUE_BROWSE_PERFORMED: AuditCategory.BUSINESS,
  WHATSAPP_SETTINGS_UNLOCKED: AuditCategory.ACCESS,
  WHATSAPP_CONFIG_RESET: AuditCategory.ADMIN,
  SUPPORT_TICKET_CREATED: AuditCategory.SUPPORT,
  SUPPORT_TICKET_REPLIED: AuditCategory.SUPPORT,
  SUPPORT_TICKET_STATUS_CHANGED: AuditCategory.SUPPORT,
  TERMS_ACCEPTED: AuditCategory.DATA,
};

/** Event types that the frontend is allowed to report via POST /api/audit/events. */
export const FRONTEND_REPORTABLE_EVENTS: Set<string> = new Set([
  AuditEventType.CONTACT_VIEWED,
  AuditEventType.CONTACT_PHONE_REVEALED,
  AuditEventType.CONTACT_PHONE_COPIED,
  AuditEventType.CONTACT_EMAIL_VIEWED,
  AuditEventType.CONTACT_CALL_CLICKED,
  AuditEventType.CONTACT_WHATSAPP_CLICKED,
  AuditEventType.CONVERSATION_VIEWED,
  AuditEventType.CONVERSATION_CONTACT_OPENED,
  AuditEventType.WHATSAPP_SETTINGS_UNLOCKED,
]);
